name: .NET Core

on: [push, pull_request]

jobs:

  build:
    name: Initialize build on .NET Core

    runs-on: windows-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v3


    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore


    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

 
