name: .NET Core Desktop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: windows-latest  
   
    steps:
    - name: Checkout
      uses: actions/checkout@v3


    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Go to the path | install dependencies
      run: |
        cd src\WPF-MVVM
        dotnet restore
        
    - name: build
      run: |
        cd src\WPF-MVVM
        dotnet build -c Debug --no-restore
    - name: Test
      run: |
         cd src\WPF-MVVM
         dotnet test --no-restore --verbosity normal
        
